/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.aereopuerto;
import Modelo.pasajeros;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author EDD
 */
public class frmAereopuerto extends javax.swing.JFrame {

    int DimensionX = 15;
    int DimensionY = 10;
    int TamX = 0;
    int TamY = 0;
    static final int TableroX = 600;
    static final int TableroY = 600;
    //Matriz de botones
    JButton[][] MatrizBotones;
    aereopuerto objar;
    pasajeros objp;
    double precio = 50;

    public frmAereopuerto() {
        initComponents();
        objar = new aereopuerto(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new elaprendiz.gui.panel.PanelImage();
        labelHeader1 = new elaprendiz.gui.label.LabelHeader();
        jPanel1 = new javax.swing.JPanel();
        clockFace1 = new elaprendiz.gui.varios.ClockFace();
        clockDigital1 = new elaprendiz.gui.varios.ClockDigital();
        labelBackgroundTitle1 = new elaprendiz.gui.label.LabelBackgroundTitle();
        lblFecha = new javax.swing.JLabel();
        pnlAsientos = new elaprendiz.gui.panel.PanelImage();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelImage4 = new elaprendiz.gui.panel.PanelImage();
        labelCustom2 = new elaprendiz.gui.label.LabelCustom();
        labelCustom3 = new elaprendiz.gui.label.LabelCustom();
        labelCustom4 = new elaprendiz.gui.label.LabelCustom();
        labelCustom5 = new elaprendiz.gui.label.LabelCustom();
        labelCustom6 = new elaprendiz.gui.label.LabelCustom();
        labelCustom7 = new elaprendiz.gui.label.LabelCustom();
        labelCustom8 = new elaprendiz.gui.label.LabelCustom();
        labelCustom9 = new elaprendiz.gui.label.LabelCustom();
        txtCodigo = new elaprendiz.gui.textField.TextFieldRound();
        txtNombre = new elaprendiz.gui.textField.TextFieldRound();
        txtApellido = new elaprendiz.gui.textField.TextFieldRound();
        lblCosto = new elaprendiz.gui.label.LabelCustom();
        lblfechaf = new elaprendiz.gui.label.LabelCustom();
        cmbOrigen = new javax.swing.JComboBox<>();
        labelCustom11 = new elaprendiz.gui.label.LabelCustom();
        cmbDestino = new javax.swing.JComboBox<>();
        cmbAer = new javax.swing.JComboBox<>();
        lblAsiento = new elaprendiz.gui.label.LabelCustom();
        buttonIcon1 = new elaprendiz.gui.button.ButtonIcon();
        labelCustom12 = new elaprendiz.gui.label.LabelCustom();
        labelCustom13 = new elaprendiz.gui.label.LabelCustom();
        panelImage5 = new elaprendiz.gui.panel.PanelImage();
        buttonAqua1 = new elaprendiz.gui.button.ButtonAqua();
        ltspasajeros = new java.awt.List();
        buttonAero1 = new elaprendiz.gui.button.ButtonAero();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/58.jpg"))); // NOI18N

        labelHeader1.setText("Bienvenido al aereopuerto Catastrofe");
        labelHeader1.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N

        lblFecha.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBackgroundTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clockDigital1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBackgroundTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pnlAsientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fighter Jet Silhouette 5 (Small).jpg"))); // NOI18N

        javax.swing.GroupLayout pnlAsientosLayout = new javax.swing.GroupLayout(pnlAsientos);
        pnlAsientos.setLayout(pnlAsientosLayout);
        pnlAsientosLayout.setHorizontalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlAsientosLayout.setVerticalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelCustom2.setText("Codigo Vuelo");

        labelCustom3.setText("Nombre Pasajero");

        labelCustom4.setText("Apellido pasajero");

        labelCustom5.setText("Fecha Compra");

        labelCustom6.setText("Aereolinea");

        labelCustom7.setText("Destino");

        labelCustom8.setText("Asiento");

        labelCustom9.setText("Costo del Boleto");

        txtCodigo.setText("12345");

        txtNombre.setText("Edison ");

        txtApellido.setText("Vaca ");

        lblCosto.setText("0");
        lblCosto.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N

        lblfechaf.setText("labelCustom1");

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ibarra", "Quito", "Guayaquil", "Cuenca", "Manta", "Galapagos" }));

        labelCustom11.setText("Origen");

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ibarra", "Quito", "Guayaquil", "Cuenca", "Manta", "Galapagos" }));

        cmbAer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tame", "Icaro", "Emigrates", "Aeroga", "Air", "Condorl" }));

        lblAsiento.setText("0");
        lblAsiento.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N

        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_over.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");
        buttonIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIcon1ActionPerformed(evt);
            }
        });

        labelCustom12.setText("Fila");

        labelCustom13.setText("Asiento");

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage4Layout.createSequentialGroup()
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelImage4Layout.createSequentialGroup()
                        .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfechaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAer, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelImage4Layout.createSequentialGroup()
                        .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbOrigen, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbDestino, javax.swing.GroupLayout.Alignment.TRAILING, 0, 235, Short.MAX_VALUE))
                            .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(panelImage4Layout.createSequentialGroup()
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage4Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(labelCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage4Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImage4Layout.createSequentialGroup()
                                .addComponent(labelCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfechaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar Pasajeros ", panelImage4);

        buttonAqua1.setText("Ver pasajeros");
        buttonAqua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage5Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(buttonAqua1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addComponent(ltspasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage5Layout.createSequentialGroup()
                .addComponent(buttonAqua1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ltspasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver pasajeros", panelImage5);

        buttonAero1.setText("buttonAero1");
        buttonAero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(pnlAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void ObtenerTamanioObjetos(int cantX, int cantY) {
        TamX = TableroX / cantX;
        TamY = TableroY / cantY;
    }

    private void RedibujarTablero() {
        //Se valida los componentes del elemento pnlTablero
        pnlAsientos.validate();

        //Se redibuja el elemento pnlTablero y sus componentes hijos
        pnlAsientos.repaint();
    }

    private void Click(JButton btn) {
        int asiento = JOptionPane.showConfirmDialog(null, "Realmente Deseas Este Asiento ", "Verificar Asiento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (asiento == JOptionPane.YES_OPTION) {

            btn.setEnabled(false);
            lblAsiento.setText("" + btn.getText());
//            lblCosto.setText(""+(precio+50));

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione Su Asiento ");
        }

        // JOptionPane.showMessageDialog(this, "Soy el boton en la posición: " + btn.getToolTipText());
    }

    public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        return formato.format(fecha);

    }
    double preciofinal = 0;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        lblFecha.setText(fechaactual());
        lblfechaf.setText(fechaactual());
//Se settea el tamaño de la matriz de botones
        MatrizBotones = new JButton[DimensionX][DimensionY];
        //Se settea el tamaño de gridLayout de nuestro panel del tablero
        pnlAsientos.setLayout(new GridLayout(DimensionX, DimensionY));
        //Se obtiene el tamaño de los botones acorde a su cantidad
        ObtenerTamanioObjetos(DimensionX, DimensionY);
        //Se declaran los contadores a utilizar
        int contadorX, contadorY;
        //Se recorre la dimension X desde 0 hasta DimensionX
        for (contadorX = 0; contadorX < DimensionX; contadorX++) {

            //Se recorre la dimension Y desde 0 hasta DimensionY
            for (contadorY = 0; contadorY < DimensionY; contadorY++) {

//                if (contadorX>=0&&contadorX<5) {
//                    precio=precio+30;
//                    lblCosto.setText(""+precio);
////                } if (contadorX>5&&contadorX<=10) {
////                    preciofinal=precio+20;
////                    lblCosto.setText(""+preciofinal);
////                } if (contadorX>10&&contadorX<=15) {
////                    preciofinal=precio+20;
////                    lblCosto.setText(""+preciofinal);
////                }
                //Se crea un nuevo objeto de tipo JButton
                JButton btnNuevo = new JButton();
                //Se le asignan sus dimensiones (ancho, alto)
                btnNuevo.setSize(TamX, TamY);
                //Se asigna un texto con la posición del botón en la matriz al botón, al tooltip del botón
                btnNuevo.setToolTipText(Integer.toString(contadorX) + "/" + Integer.toString(contadorY));

                btnNuevo.setText(Integer.toString(contadorX + 1) + "/" + Integer.toString(contadorY + 1));
                btnNuevo.setBackground(Color.BLUE);

                //Se agrega a la matriz el botón recien creado
                MatrizBotones[contadorX][contadorY] = btnNuevo;
                //Se agrega un nuevo evento que maneje la acción clic sobre el botón creado
                MatrizBotones[contadorX][contadorY].addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        Click(btnNuevo);
                    }
                });
                //Se agrega al panel 
                pnlAsientos.add(MatrizBotones[contadorX][contadorY]);
                //Se redibuja el panel
                RedibujarTablero();
            }//Fin For - Y
        }//Fin For - X


    }//GEN-LAST:event_formWindowOpened

    private void buttonAero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero1ActionPerformed
        objar = new aereopuerto(3);
        pasajeros objp1 = new pasajeros(005, "17", "ibarra", "quito", "antony", "vaca", "17/12/2019", "Tame", "economica", 38.50);
        objar.agregarCuenta(objp1);
        pasajeros objp2 = new pasajeros(007, "22", "quito", "guayaquil", "Jorje", "vaca", "17/12/2019", "vuelafacil", "premium", 50.0);
        objar.agregarCuenta(objp2);
        pasajeros objp3 = new pasajeros(7, "39", "guayaquil", "ibarra", "Edison", "vaca", "17/12/2019", "siemprevuela", "pro", 80.0);
        objar.agregarCuenta(objp3);
        System.out.println("exito");
        for (int i = 0; i < objar.getTam(); i++) {
            ltspasajeros.add("" + objar.getVec()[i].getNombrep());
//            lista1.addItem(""+objar.getVec()[i].getNombrep());
        }
    }//GEN-LAST:event_buttonAero1ActionPerformed
    public void limpiar() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        lblAsiento.setText("0");

    }
    private void buttonIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIcon1ActionPerformed
        int vuelo = Integer.parseInt(txtCodigo.getText());

        String origen = cmbOrigen.getSelectedItem().toString(),
                destino = cmbDestino.getSelectedItem().toString(),
                nombrep = txtNombre.getText(),
                apellido = txtApellido.getText(),
                fecha = lblfechaf.getText(),
                aereolinea = cmbAer.getSelectedItem().toString(),
                asiento = lblAsiento.getText();

        objp = new pasajeros(vuelo, asiento, origen, destino, nombrep, apellido, fecha, aereolinea, "ejecutivo", 35.14);
        objar.agregarCuenta(objp);
        limpiar();
    }//GEN-LAST:event_buttonIcon1ActionPerformed

    private void buttonAqua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua1ActionPerformed
        ltspasajeros.removeAll();
        for (int i = 0; i < objar.getTam(); i++) {
            ltspasajeros.add("" + objar.getVec()[i].getVuelo());
            ltspasajeros.add("" + objar.getVec()[i].getNombrep());
            ltspasajeros.add("" + objar.getVec()[i].getApellido());
            ltspasajeros.add("" + objar.getVec()[i].getAsiento());
            ltspasajeros.add("" + objar.getVec()[i].getOrigen());
            ltspasajeros.add("" + objar.getVec()[i].getDestino());
            ltspasajeros.add("" + objar.getVec()[i].getFecha());
            ltspasajeros.add("" + objar.getVec()[i].getCategoria());
            ltspasajeros.add("" + objar.getVec()[i].getPreciob());

            ltspasajeros.add("___________________________");
        }
    }//GEN-LAST:event_buttonAqua1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAereopuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAereopuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAereopuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAereopuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAereopuerto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonAero buttonAero1;
    private elaprendiz.gui.button.ButtonAqua buttonAqua1;
    private elaprendiz.gui.button.ButtonIcon buttonIcon1;
    private elaprendiz.gui.varios.ClockDigital clockDigital1;
    private elaprendiz.gui.varios.ClockFace clockFace1;
    private javax.swing.JComboBox<String> cmbAer;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private elaprendiz.gui.label.LabelBackgroundTitle labelBackgroundTitle1;
    private elaprendiz.gui.label.LabelCustom labelCustom11;
    private elaprendiz.gui.label.LabelCustom labelCustom12;
    private elaprendiz.gui.label.LabelCustom labelCustom13;
    private elaprendiz.gui.label.LabelCustom labelCustom2;
    private elaprendiz.gui.label.LabelCustom labelCustom3;
    private elaprendiz.gui.label.LabelCustom labelCustom4;
    private elaprendiz.gui.label.LabelCustom labelCustom5;
    private elaprendiz.gui.label.LabelCustom labelCustom6;
    private elaprendiz.gui.label.LabelCustom labelCustom7;
    private elaprendiz.gui.label.LabelCustom labelCustom8;
    private elaprendiz.gui.label.LabelCustom labelCustom9;
    private elaprendiz.gui.label.LabelHeader labelHeader1;
    private elaprendiz.gui.label.LabelCustom lblAsiento;
    private elaprendiz.gui.label.LabelCustom lblCosto;
    private javax.swing.JLabel lblFecha;
    private elaprendiz.gui.label.LabelCustom lblfechaf;
    private java.awt.List ltspasajeros;
    private elaprendiz.gui.panel.PanelImage panelImage1;
    private elaprendiz.gui.panel.PanelImage panelImage4;
    private elaprendiz.gui.panel.PanelImage panelImage5;
    private elaprendiz.gui.panel.PanelImage pnlAsientos;
    private elaprendiz.gui.textField.TextFieldRound txtApellido;
    private elaprendiz.gui.textField.TextFieldRound txtCodigo;
    private elaprendiz.gui.textField.TextFieldRound txtNombre;
    // End of variables declaration//GEN-END:variables
}
